### ISSUE TITLE
How will the output look like

### ISSUE THREAD

**Issue by ilovemyself-pooh** [susobhang70/shapley_value#1]
Hi there,
How will the output of this code look like?

**Comment by susobhang70** [comment]
It'll print a list of size N (the number of players) indicating the Shapley values for each player

**Comment by ilovemyself-pooh** [comment]
I dont understand this part of your instruction python shapley.py <filename>, this means I have to load the project and run the shapley.py file right, where do I adjust the N value?

**Comment by susobhang70** [comment]
As clearly mentioned in the README, you need to run it like - `python.py shapley.py <inputfilename>`

The file which you provide will have the "N" value (as described in the input section). For sample input files, refer to the `Testcases/` folder.
