### ISSUE TITLE
V value

### ISSUE THREAD

**Issue by ilovemyself-pooh** [susobhang70/shapley_value#2]
Hi, I am sorry to bother you again. May I please ask how did you derive the parameter for V? What is the function of the V? When I went through your text files TC1.Text. I found this N = 4
1, 1, 2, 1, 3, 4, 4, 3, 4, 4, 5, 7, 6, 6, 8

The value is of N is clear, how did you get the following values : 1, 1, 2, 1, 3, 4, 4, 3, 4, 4, 5, 7, 6, 6, 8 (text file TC1.Text)

**Comment by susobhang70** [comment]
> how did you derive the parameter for V?

Please understand, the coalition values are always considered to be given when finding Shapley value. If you are not familiar with Shapley value definition, please take a look at [this](https://en.wikipedia.org/wiki/Shapley_value)

> how did you get the following values : 1, 1, 2, 1, 3, 4, 4, 3, 4, 4, 5, 7, 6, 6, 8

So, those are the values of the coalitions for that particular characteristic form (or TU) game. You don't **get** the values, they are given to you / available to you, for which you find the Shapley value.

As for the order for which coalitions these values correspond to, refer README. They're basically in this order - v(1),..,v(n), v(12),..., v(1n), v(23).., v(2n),..,v(n-1n), v(123),v(124),...,v(12n), v(234)..,..,v(12..n)

**Comment by ilovemyself-pooh** [comment]
Thank you for your reply. I am very new to the game theory, I came across this paper http://dad.ecn.ulaval.ca/pdf_files/shap_dec_aj.pdf, from which I understand that a Shapley Value can be calculated with a V value. Could you please help me on this?

**Comment by susobhang70** [comment]
Referencing the document you linked, 

> mv(S, k) = (v (S ∪ {k}) − v(S)).

Here, S is the coalition, and k is a player being added to the coalition S. So **v (S ∪ {k})** is the value of the coalition after k has joined S, and **v(S)** being the initial value of the coalition S. The difference essentially calculates the marginal contribution of player k after being added to a coalition S, as explained in the first part of the document.

> Shapley Value can be calculated with a V value

That V value is nothing but v(1),..,v(n), v(12),..., v(1n), v(23).., v(2n),..,v(n-1n), v(123),v(124),...,v(12n), v(234)..,..,v(12..n)

I guess you're having difficulties in the last part of the document (with the V vector). So referencing the same, 
> Let the elements v<sub>l</sub> of the 1 × n vector V = (v<sub>1</sub>, ...., v<sub>2<sup>n</sup></sub> )

The **V** here is nothing but the set of numbers that I've referenced above. If you look carefully, you'll realize that there are 2<sup>n</sup> values, where n is the number of players in the game. Why? N players means 2<sup>n</sup> possible coalitions (I hope you can figure out why :blush: ), and thus those many values (one for each possible coalition)

Hope that helps!

**Comment by ilovemyself-pooh** [comment]
Thank you for your reply. I just want to clarify on this 
Refer to your code and assume the input file is "TC1.txt", So

N = 4
S = [[0], [1], [2], [3], [0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 3], [0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3], [0, 1, 2, 3]]
V = [v([0]), v([1]), v([2]), v([3]), v([0, 1]), ..., v([0, 1, 2, 3])] = [1, 1, 2, 1, 3, ..., 8]

My question is, how you calculated the Vs and ended up with 

For example, v([0]) = 1, v([1]) = 1 , ..., and v([0, 1, 2, 3]) = 8

**Comment by susobhang70** [comment]
> My question is, how you calculated the Vs and ended up with...

Those have **not** been calculated - rather my program assumes those values to be given as input, thus present in the test/input files.

**Comment by ilovemyself-pooh** [comment]
Thank you for your reply. Let me clarify again, N is the number of player, S is the coalition value, let say N is 5, then there would be 32 different coalition values right?

**Comment by ilovemyself-pooh** [comment]
Adding to that,
v will now be V(1).....v(32) is it? If yes, what will be the value v(6) then or what does it represent?

**Comment by susobhang70** [comment]
> let say N is 5, then there would be 32 different coalition values right?

You are correct.

> v will now be V(1).....v(32) is it?

Yes

> what will be the value v(6) then or what does it represent?

So, as per the way I mentioned in the input section, the order of values to my program will be - 
> v(1),..,v(n), v(12),..., v(1n), v(23).., v(2n),..,v(n-1n), v(123),v(124),...,v(12n), v(234)..,..,v(12..n)

Given that N = 5, so it goes v([1]) v([2]) v([3]) v([4]) v([5]), and the next i.e. 6th value will be v([1,2]), i.e. value of coalition of players 1 and 2. It'll be followed by v([1,3])...v([1,5]), v([2,3]),...v([2,5]) and so on as described above.

**Comment by ilovemyself-pooh** [comment]
Thank you for the reply. Does this means that the V value will always be random? Is there any way to fix the V value to calculate the Shapley Value? I have read some papers who are using Shapley Value for Feature Selection, having the V as a random value, wouldnt the Shapley Value be a differing value (unless I fix the V value) since the V value is a random value?

**Comment by susobhang70** [comment]
> Does this means that the V value will always be random? Is there any way to fix the V value to calculate the Shapley Value?

They are not **random**, they will depend on how the game is defined. If I'm getting this correctly, you're looking for examples and applications of Shapley Value. If you're interested, please take a look at this [Lecture Note on Shapley Value](http://lcm.csa.iisc.ernet.in/gametheory/ln/web-cp5-shapley.pdf). Take a look at the four examples, and the problems listed at the end of the document (Q7 and Q11 for example). Maybe this'll give you an idea how Shapley Value applies, and how "V" values vary from game to game.

> I have read some papers who are using Shapley Value for Feature Selection, having the V as a random value, wouldnt the Shapley Value be a differing value (unless I fix the V value) since the V value is a random value?

If V is random and changing, of course Shapley Value will change. However, I have no domain knowledge about feature selection using Shapley Value, so I won't be able to give you more insight as to why they do it, and how it makes sense.
