### ISSUE TITLE
The coalition order

### ISSUE THREAD

**Issue by EvaluationResearch** [susobhang70/shapley_value#3]
Hi ,
9 players should have 511 coalitions, that is N=9.
3 players (in a team with 9 members)will have 84 coalitions . As your document, i have the following list:
v(123),v(124),v(125),v(126),v(127),v(128),v(129),
v(234),v(235),...v(239),
v(345),v(346)..........v(349)
...
v(789)
Above is 24 coalitions, so still have 84-24=60 coalitions, would you like to let me know what’s next?
V(134) v(135) ...v(139)
V(145)v(146)...v(149)
V(156)v(157)..v(159)
...
V(189)
Are these right?

The order of these data seems to have some impact on the result.
Much appreciated it if any help could be provided.
Thanks.

**Comment by EvaluationResearch** [comment]
Any one could help?

**Comment by susobhang70** [comment]
Sorry, I know this is a super late response. But for anyone who comes looking into this - they are basically in this order - v(1),..,v(n), v(12),..., v(1n), v(23).., v(2n),..,v(n-1n), v(123),v(124),...,v(12n), v(234)..,..,v(12..n)

So please do the same for N=9.
